apiVersion: v1
kind: Namespace
metadata:
  name: eshop
  labels:
    app.kubernetes.io/name: eshop
    app.kubernetes.io/instance: eshop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: eshop
  name: pv-micro-h2o-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

---
apiVersion: v1
kind: Service
metadata:
  namespace: eshop
  name: stateful-micro-h2o-0
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: stateful-micro-h2o-0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eshop
  name: stateful-micro-h2o-0
  labels:
    app: stateful-micro-h2o-0
spec:
  selector:
    matchLabels:
      app: stateful-micro-h2o-0
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: stateful-micro-h2o-0
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      volumes:
        - name: pv-micro-h2o-0-storage
          persistentVolumeClaim:
            claimName: pv-micro-h2o-0
      containers:
        - name: stateful-micro-h2o-0
          image: maxmorev/stateful-micro-h2o:latest
          volumeMounts:
            - name: v-micro-h2o-0-storage
              mountPath: /opt/micro/h2o
          ports:
            - containerPort: 8080
              name: stateful-micro-h2o-0
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m" # 1/4 core
            limits:
              memory: "250Mi"
              cpu: "500m" # 1/2 core
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 3
            timeoutSeconds: 5
            periodSeconds: 3
            failureThreshold: 1
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            periodSeconds: 8
            failureThreshold: 1
