# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Echo first
        run: echo 'GITHUB_RUN_NUMBER -> ${{ github.run_number }}'
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: ./mvnw package
      - name: Build and push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: maxmorev/stateful-micro-h2o
          tags: 0.0.${{ github.run_number }}
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
#      - name: set kubectl context
#        uses: azure/k8s-set-context@v1
#        with:
#          method: kubeconfig
#          kubeconfig: ${{ secrets.DIGITALOCEAN_K8S_CONFIG }}
#        id: setcontext
      - name: Update deployment file
        run: TAG='0.0.$(echo $github.run_number | head -c7)' && sed -i 's|maxmorev/stateful-micro-h2o:latest|maxmorev/stateful-micro-h2o:'${TAG}'|' $GITHUB_WORKSPACE/stateful-micro-h2o-deploy.yaml
      - name: Check image version
        run: cat $GITHUB_WORKSPACE/stateful-micro-h2o-deploy.yaml | grep image
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save k8s-eshop
      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/stateful-micro-h2o-deploy.yaml
#      - uses: Azure/k8s-deploy@v1
#        with:
#          namespace: eshop
#          manifests: |
#            stateful-micro-h2o-deploy.yaml
#          images: maxmorev/stateful-micro-h2o:0.0.${{ github.run_number }}
#          kubectl-version: latest